# Facility configuration for volleyball league
name: "Volleyball League 2025"

# Team configuration
team_counts: [13, 10, 9]  # Number of teams in each division
# team_counts: [12, 12, 8]  # Number of teams in each division
games_per_season: 6
games_per_day: 1

# Time slot configuration
# Each entry contains a time and the court layout for that time slot
# 1 indicates an active court, 0 indicates inactive
time_slots:
  - time: "12:00"
    courts: [1, 1, 0, 0]  # Court 1-4 layout for 01:00
  - time: "13:00"
    courts: [1, 1, 1, 1]  # Court 1-4 layout for 01:00
  - time: "14:00"
    courts: [1, 1, 1, 1]  # Court 1-4 layout for 02:00
  - time: "15:00"
    courts: [1, 1, 1, 1]  # Court 1-4 layout for 03:00
  - time: "16:00"
    courts: [1, 1, 0, 0]  # Court 1-4 layout for 04:00

# Schedule configuration
dates:
  - "6/22/2025"
  - "6/29/2025"
  - "7/6/2025"
  - "7/13/2025"
  - "7/20/2025"
  - "7/27/2025" 