# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('team', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='team_count',
        ),
        migrations.AddField(
            model_name='league',
            name='courts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='league',
            name='divisions',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
