# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20160110_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team',
            new_name='court',
        ),
        migrations.AddField(
            model_name='game',
            name='ref',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.IntegerField(default=0),
        ),
    ]
